package IR.Type;

public enum TypeEnum {
	VOID,
	FUNCTION,
	// stands for null pointer; type is to be determined
	NULL,
	// first class type: can be generated by instruction
	//   single value types: considered as reg
	INT, POINTER,
	//   label type
	LABEL,
	//   aggregate types: derived types
	STRUCT, ARRAY,
}
